name: Backend

on: [workflow_dispatch, push, pull_request]

jobs:
  run:
    uses: flarum/framework/.github/workflows/REUSABLE_backend.yml@main
    with:
      enable_backend_testing: true       # PHPUnit testlerini etkinleştir
      enable_phpstan: false              # PHPStan'ı devre dışı bırak
      backend_directory: .               # composer.json dosyasının bulunduğu dizin
