name: Build and Transpile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Doğru dizine geçiş yapıyoruz, çünkü package.json burada
    - name: Change to js directory
      run: cd js  # Bu adım js dizinine geçiş yapar

    # Bağımlılıkları yükleyin
    - name: Install dependencies
      run: npm install  # Burada js/package.json dosyasındaki bağımlılıkları yüklüyoruz

    # Webpack derleme işlemi (geliştirme modunda tek seferlik derleme)
    - name: Run Webpack in Watch Mode
      run: |
        cd js
        npm run build  # Bu, üretim modunda derleme yapar

    # (Opsiyonel) Webpack geliştirme modunda sürekli derleme
    - name: Run Webpack Dev (alternatif)
      run: |
        cd js
        npm run dev  # Geliştirme modunda derleme yapılır
