name: Publish package to GitHub Packages
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@organizationName'  # Organizasyon isminizi buraya ekleyin

      # Install dependencies
      - name: Install dependencies
        run: |
          cd js
          yarn

      # Publish package to GitHub Packages
      - name: Publish package
        run: |
          cd js
          yarn publish --access restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}  # GitHub Secrets'den token'ı alıyoruz
