name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # js dizinine geçiş yapıyoruz, çünkü package.json orada
      - name: Change to js directory
        run: cd js

      # Bağımlılıkları yükleyin ve projeyi derleyin
      - name: Install dependencies and build
        run: |
          npm install  # js/package.json içinde bağımlılıkları yüklüyoruz
          npm run build  # js dizinindeki build komutunu çalıştırıyoruz
