name: Publish to NPM

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'

      # Change directory to js folder
      - name: Change to js directory
        run: cd js

      # Install dependencies and build
      - name: Install dependencies and build 🔧
        run: |
          cd js
          npm ci && npm run build

      # Publish package on NPM
      - name: Publish package on NPM 📦
        run: |
          cd js
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}  # GitHub Secrets'den token'ı alıyoruz
