name: Build and Deploy Flarum Extension

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Flarum genellikle Node.js 16 ile uyumludur.

      # 3. Install dependencies using npm
      - name: Install dependencies
        run: npm install

      # 4. Run the build process (production build)
      - name: Build production files
        run: npm run build

      # 5. Upload build artifacts for later use (updated to use v4)
      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            js/dist/forum.js
            js/dist/forum.js.map
            # Add any other build output files if needed

      # 6. Commit and push the build files (optional step, if you want to push the build files)
      - name: Commit dist files
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add js/dist/*
          git commit -m "Update dist files"
          git push origin main
        if: success() && github.event_name == 'push'
