name: Publish to NPM

on:
  release:
    types: [created] # Yeni bir sürüm oluşturulduğunda çalışır.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Kodu GitHub deposundan çek
      - name: Checkout code
        uses: actions/checkout@v2

      # Node.js ortamını ayarla
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x' # Node sürümü
          registry-url: 'https://registry.npmjs.org'

      # .npmrc dosyasını ayarla (GitHub Token kullanarak)
      - name: Configure npm with GitHub token
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      # Bağımlılıkları yükle ve projeyi derle
      - name: Install dependencies and build
        working-directory: js
        run: |
          npm ci # Temiz yükleme
          npm run build

      # NPM'ye paketi yayınla
      - name: Publish to NPM
        working-directory: js
        run: npm publish --access public
